version: '3.1'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: postgers
      POSTGRES_DB: mydlala
      TZ: US/Eastern
      PGTZ: US/Eastern
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/mydlala.sql
    ports:
      - 5432:5432